using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Text;
using static Content.Shared.Mining.Components.SharedFurnaceComponent;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Furnace.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class FurnaceWindow : DefaultWindow
    {

        public FurnaceWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
           
        }
    }
}
